network:
  version: 2
  renderer: networkd
  ethernets:
    eno1:
      dhcp4: true
      dhcp4: true
      addresses:
        - 192.168.0.111/24   # Your persistent Virtual IP
        - 192.168.10.110/24
      nameservers:
        addresses: [192.168.0.110, 192.168.0.197, 192.168.0.1]
      routes:
        - to: 0.0.0.0/0
          via: 192.168.0.1



