network:
  version: 2
  renderer: networkd
  ethernets:
    enp8s8:
      dhcp4: false
      addresses: [192.168.0.197/24,192.168.10.197/24]
      nameservers:
        addresses: [192.168.0.197, 192.168.0.110, 192.168.0.1]
      routes:
        - to: 0.0.0.0/0
          via: 192.168.0.1

